--select deptno,case deptno
--when 10 then 'a'
--when 20 then 'b'
--else 'z'
--end as dept_name
--from emp;

--3-05
--select VENDOR_NAME,VENDOR_CONTACT_LAST_NAME,VENDOR_CONTACT_FIRST_NAME
--from VENDORS
--ORDER BY VENDOR_CONTACT_LAST_NAME,VENDOR_CONTACT_FIRST_NAME
--3-06
--SELECT VENDOR_CONTACT_LAST_NAME||', '||VENDOR_CONTACT_FIRST_NAME AS FULL_NAME
--FROM VENDORS
--WHERE SUBSTR(VENDOR_CONTACT_LAST_NAME,1,1) IN ('A','B','C','E')
--ORDER BY  VENDOR_CONTACT_LAST_NAME,VENDOR_CONTACT_FIRST_NAME
--3-07
--SELECT INVOICE_DUE_DATE "Due Date", INVOICE_TOTAL "Invoice Total",INVOICE_TOTAL*0.1 AS "10%",INVOICE_TOTAL*1.1 AS "Pluas 10%" 
--FROM INVOICES
--WHERE INVOICE_TOTAL BETWEEN 500 AND 1000
--ORDER BY INVOICE_DUE_DATE DESC
--3-08
--SELECT INVOICE_NUMBER "Number",INVOICE_TOTAL "Total",PAYMENT_TOTAL+CREDIT_TOTAL AS "Credits",INVOICE_TOTAL-PAYMENT_TOTAL-CREDIT_TOTAL AS "Balance Due"
--FROM INVOICES
--WHERE (INVOICE_TOTAL-PAYMENT_TOTAL-CREDIT_TOTAL)>=500
--ORDER BY INVOICE_TOTAL-PAYMENT_TOTAL-CREDIT_TOTAL DESC
--WHERE ROWNUM<=10
--3-09
--SELECT INVOICE_TOTAL-PAYMENT_TOTAL-CREDIT_TOTAL AS "Balance Due",PAYMENT_DATE
--FROM INVOICES
--WHERE PAYMENT_DATE IS NULL AND INVOICE_TOTAL-PAYMENT_TOTAL-CREDIT_TOTAL=0
--3-10
--SELECT 51000 AS "Starting Principle",51000*1.1 AS "New Principle",51000*1.1*0.065 AS "Interest",51000*1.1*0.065+51000*1.1 AS "Principle + Interest",TO_CHAR(SYSDATE,'dd-mon-yyyy hh24:mi:ss') AS "System Date" 
--FROM DUAL

--4-01
--SELECT * FROM VENDORS JOIN INVOICES 
--ON VENDORS.VENDOR_ID=INVOICES.VENDOR_ID
--4-02
--SELECT V.VENDOR_NAME,I.INVOICE_NUMBER,I.INVOICE_DATE,I.INVOICE_TOTAL-I.PAYMENT_TOTAL-I.CREDIT_TOTAL AS "BALANCE_DUE"
--FROM VENDORS V JOIN INVOICES I 
--ON V.VENDOR_ID=I.VENDOR_ID
--WHERE I.INVOICE_TOTAL-I.PAYMENT_TOTAL-I.CREDIT_TOTAL<>0
--ORDER BY V.VENDOR_NAME
--4-03
--SELECT V.VENDOR_NAME,V.DEFAULT_ACCOUNT_NUMBER AS "DEFAULT_ACCOUNT",G.ACCOUNT_DESCRIPTION AS "DESCRIPTION"
--FROM VENDORS V JOIN GENERAL_LEDGER_ACCOUNTS G
--ON V.DEFAULT_ACCOUNT_NUMBER=G.ACCOUNT_NUMBER
--ORDER BY G.ACCOUNT_DESCRIPTION,V.VENDOR_NAME
--4-04
--SELECT Ven.VENDOR_NAME,Inv.INVOICE_DATE,Inv.INVOICE_NUMBER,LI.INVOICE_SEQUENCE AS "li_sequence",LI.LINE_ITEM_AMT AS "li_amount"
--FROM VENDORS Ven JOIN INVOICES Inv ON Ven.VENDOR_ID=Inv.VENDOR_ID
--JOIN INVOICE_LINE_ITEMS LI ON LI.INVOICE_ID=Inv.INVOICE_ID 
--ORDER BY Ven.VENDOR_ID,Inv.INVOICE_DATE,Inv.INVOICE_NUMBER,LI.INVOICE_SEQUENCE
--4-05
--SELECT V1.VENDOR_ID,V1.VENDOR_NAME,V1.VENDOR_CONTACT_FIRST_NAME||', '||V1.VENDOR_CONTACT_LAST_NAME AS "CONTACT_NAME"
--FROM VENDORS V1 JOIN VENDORS V2 ON V1.VENDOR_CONTACT_LAST_NAME=V2.VENDOR_CONTACT_LAST_NAME
--ORDER BY V1.VENDOR_CONTACT_LAST_NAME
--4-06
SELECT gl.account_number, account_description
FROM general_ledger_accounts gl LEFT JOIN invoice_line_items li
  ON gl.account_number = li.account_number
WHERE li.account_number IS NULL
ORDER BY gl.account_number
--4-07
--SELECT VENDOR_NAME,'CA' AS VENDOR_STATE FROM VENDORS
--WHERE VENDOR_STATE='CA'
--UNION
--SELECT VENDOR_NAME,'Outside CA' AS VENDOR_STATE FROM VENDORS
--WHERE VENDOR_STATE<>'CA'
