-- HW5.sql -- Homework 5
--
-- XUJIAN SHAO
-- UT EID: xs2929, UTCS username: xs2929
-- C S 347, Spring 2017, Dr. P. Cannata
-- Department of Computer Science, The University of Texas at Austin
--
--13-01
SET SERVEROUTPUT ON;

DECLARE

count_product NUMBER;

BEGIN

SELECT COUNT(*)
INTO count_product
FROM PRODUCTS;

IF count_product >= 7 THEN
DBMS_OUTPUT.PUT_LINE('The number of products is greater than or equal to 7');
ELSE
DBMS_OUTPUT.PUT_LINE('The number of products is less than 7');
END IF;
END;
/

--13-02
SET SERVEROUTPUT ON;

DECLARE

COUNT_PRODUCT NUMBER;
AVG_LIST_PRICE PRODUCTS.LIST_PRICE%TYPE;

BEGIN

SELECT COUNT(*),AVG(PRODUCTS.LIST_PRICE)
INTO COUNT_PRODUCT,AVG_LIST_PRICE
FROM PRODUCTS;



IF count_product >= 7 THEN
DBMS_OUTPUT.PUT_LINE('The number of products is '||COUNT_PRODUCT);
DBMS_OUTPUT.PUT_LINE('Average list price of the products is '||AVG_LIST_PRICE);
ELSE
DBMS_OUTPUT.PUT_LINE('The number of products is less than 7');
END IF;
END;
/

--13-03
SET SERVEROUTPUT ON;

DECLARE

INTEGER_ONE INTEGER:=10;
INTEGER_TWO INTEGER:=20;

BEGIN
DBMS_OUTPUT.PUT('Common factors of '||INTEGER_ONE||' and '||INTEGER_TWO||':');
FOR i IN 1..INTEGER_ONE LOOP
IF MOD(INTEGER_ONE,i)=0 AND MOD(INTEGER_TWO,i)=0 THEN
DBMS_OUTPUT.PUT(' '||i);
END IF;
END LOOP;
DBMS_OUTPUT.NEW_LINE();

END;
/
--13-04
SET SERVEROUTPUT ON;

DECLARE

CURSOR PRODUCT_CURSOR IS
SELECT PRODUCT_NAME,LIST_PRICE FROM PRODUCTS
WHERE LIST_PRICE > 700
ORDER BY LIST_PRICE DESC;

PRODUCT_ROW PRODUCTS%ROWTYPE;

BEGIN
FOR PRODUCT_ROW IN PRODUCT_CURSOR LOOP
DBMS_OUTPUT.PUT('"'||PRODUCT_ROW.PRODUCT_NAME||'"'||','||'"'||PRODUCT_ROW.LIST_PRICE||'"'||'|');
END LOOP;
DBMS_OUTPUT.NEW_LINE();

END;
/
--13-05
SET SERVEROUTPUT ON;

BEGIN

INSERT INTO CATEGORIES VALUES (1,'Guitars');
DBMS_OUTPUT.PUT_LINE('1 row inserted');

EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('Row was not inserted - duplicate entry.');

END;
/






